spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: sasorimaxter@gmail.com
    password: ikgjwikbmtnxsufl
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false